/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libxinyoudi.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $955F1759725876F7F898C71A8A4DCDA3;

/* 1 */
struct Elf64_Sym
{
  unsigned __int32 st_name __offset(OFF64,0x3D70);
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
  unsigned __int64 st_value __off;
  unsigned __int64 st_size;
};

/* 2 */
struct Elf64_Rela
{
  unsigned __int64 r_offset;
  unsigned __int64 r_info;
  __int64 r_addend;
};

/* 3 */
struct Elf64_Dyn
{
  unsigned __int64 d_tag;
  unsigned __int64 d_un;
};

/* 4 */
struct Elf64_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file __offset(OFF64,0x3D70);
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 5 */
struct Elf64_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name __offset(OFF64,0x3D70);
  unsigned __int32 vna_next;
};

/* 6 */
struct type_info;

/* 7 */
struct __class_type_info;

/* 8 */
typedef unsigned __int64 size_t;

/* 9 */
struct xinyoudi::ApkUtils;

/* 10 */
struct xinyoudi::FileRef;

/* 11 */
struct xinyoudi::LuaFileUtils;

/* 12 */
struct std::exception;

/* 13 */
struct std::bad_exception;

/* 14 */
struct std::bad_alloc;

/* 15 */
struct std::bad_array_new_length;

/* 16 */
struct std::bad_array_length;

/* 17 */
struct std::logic_error;

/* 18 */
struct std::runtime_error;

/* 19 */
struct std::type_info;

/* 20 */
struct std::bad_cast;

/* 21 */
struct std::bad_typeid;

/* 22 */
struct std::nothrow_t;

/* 23 */
struct std::invalid_argument;

/* 24 */
struct std::underflow_error;

/* 25 */
struct std::domain_error;

/* 26 */
struct std::length_error;

/* 27 */
struct std::out_of_range;

/* 28 */
struct std::range_error;

/* 29 */
struct std::overflow_error;

/* 30 */
struct std::__ndk1;

/* 31 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 32 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 33 */
typedef __n64 int8x8_t;

/* 34 */
typedef __n64 uint8x8_t;

/* 35 */
typedef __n64 int16x4_t;

/* 36 */
typedef __n64 int32x2_t;

/* 37 */
typedef __n64 uint16x4_t;

/* 38 */
typedef __n64 uint32x2_t;

/* 39 */
typedef __n128 int8x16_t;

/* 40 */
typedef __n128 int16x8_t;

/* 41 */
typedef __n128 int32x4_t;

/* 42 */
typedef __n128 int64x2_t;

/* 43 */
typedef __n128 uint8x16_t;

/* 44 */
typedef __n128 uint16x8_t;

/* 45 */
typedef __n128 uint32x4_t;

/* 46 */
typedef __n128 uint64x2_t;

/* 47 */
typedef __n64 poly8x8_t;

/* 48 */
typedef __n64 poly16x4_t;

/* 49 */
typedef __n128 poly16x8_t;

/* 50 */
typedef __n128 poly8x16_t;

/* 51 */
typedef __n64 float16x4_t;

/* 52 */
typedef __n64 float32x2_t;

/* 53 */
typedef __n128 float16x8_t;

/* 54 */
typedef __n128 float32x4_t;

/* 55 */
typedef __n128 float64x2_t;

/* 56 */
typedef __n128 poly128_t;

/* 57 */
typedef int16x4_t int16x2_t;

/* 58 */
typedef uint16x4_t uint16x2_t;

/* 59 */
typedef float16x4_t float16x2_t;

/* 60 */
struct __va_list_tag
{
  void *__stack;
  void *__gr_top;
  void *__vr_top;
  int __gr_offs;
  int __vr_offs;
};

/* 61 */
typedef __va_list_tag gcc_va_list[1];

/* 62 */
typedef union $955F1759725876F7F898C71A8A4DCDA3 pthread_mutex_t;

/* 66 */
struct __pthread_internal_list
{
  struct __pthread_internal_list *__prev;
  struct __pthread_internal_list *__next;
};

/* 65 */
typedef struct __pthread_internal_list __pthread_list_t;

/* 64 */
struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  unsigned int __nusers;
  int __kind;
  int __spins;
  __pthread_list_t __list;
};

/* 63 */
union $955F1759725876F7F898C71A8A4DCDA3
{
  struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s __data;
  char __size[40];
  __int64 __align;
};

